
import type { Asset } from './firebase/firestoreService';
import { v4 as uuidv4 } from 'uuid';

export const DUMMY_ASSETS: Asset[] = [
  {
    id: uuidv4(),
    creator: 'BrandC',
    name: 'Sparkle Soap Ad',
    type: 'Video',
    length: '15s',
    campaign: 'Q4 Push',
    tags: 'UGC, Holiday, Fast Pacing, Clear CTA',
    creationDate: '2024-07-28',
    contentSnId: 'VID-BRAC-Q4PU-20240728-ABCD',
    daypart: 'Evening',
    spotLength: '15s',
    parentCompany: 'Global Consumer Goods Inc.',
    brand: 'BrandC',
    product: 'Sparkle Soap',
    brandSafety: { isSafe: true, flags: [], reasoning: '' },
    status: 'Picked Up',
    contentType: 'Branded',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 88,
    roas: 8.5,
    spend: 1200,
    cpa: 15,
  },
  {
    id: uuidv4(),
    creator: 'InfluencerA',
    name: 'Summer Dress Promo',
    type: 'Image',
    length: 'N/A',
    campaign: 'Summer Sale',
    tags: 'Lifestyle, Beach, Humor',
    creationDate: '2024-06-15',
    contentSnId: 'IMG-INFA-SUMS-20240615-EFGH',
    daypart: 'Afternoon',
    spotLength: 'N/A',
    parentCompany: 'Sunshine Apparel',
    brand: 'CoolWave',
    product: 'Summer Dress',
    brandSafety: { isSafe: false, flags: ['Contextual Issues'], reasoning: 'Creative appears to promote unhealthy body standards.' },
    status: 'Rejected',
    contentType: 'Endorsed',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 45,
    roas: 7.9,
    spend: 2500,
    cpa: 18,
  },
  {
    id: uuidv4(),
    creator: 'BrandC',
    name: 'Shine Shampoo Commercial',
    type: 'Video',
    length: '30s',
    campaign: 'Holiday Promotion',
    tags: 'Product, Demo, Emotional Storytelling',
    creationDate: '2024-07-20',
    contentSnId: 'VID-BRAC-HOLI-20240720-IJKL',
    daypart: 'Morning',
    spotLength: '30s',
    parentCompany: 'Global Consumer Goods Inc.',
    brand: 'BrandC',
    product: 'Shine Shampoo',
    brandSafety: { isSafe: true, flags: [], reasoning: '' },
    status: 'In Review',
    contentType: 'Branded',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 64,
    roas: 7.1,
    spend: 5000,
    cpa: 22,
  },
  {
    id: uuidv4(),
    creator: 'UGC_CreatorX',
    name: 'Smart Widget Testimonial',
    type: 'Video',
    length: '10s',
    campaign: 'Q3 Brand',
    tags: 'Testimonial, Single Message Focus',
    creationDate: '2024-05-10',
    contentSnId: 'VID-UGCX-Q3BR-20240510-MNOP',
    daypart: 'Late Night',
    spotLength: '15s',
    parentCompany: 'Tech Innovations LLC',
    brand: 'GadgetPro',
    product: 'Smart Widget',
    brandSafety: { isSafe: true, flags: [], reasoning: '' },
    status: 'Ready for Publisher',
    contentType: 'UGC',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 92,
    roas: 6.8,
    spend: 800,
    cpa: 25,
  },
  {
    id: uuidv4(),
    creator: 'InfluencerB',
    name: 'Marketing Tool Guide',
    type: 'Blog Post',
    length: 'N/A',
    campaign: 'Lead Gen',
    tags: 'How-to, Guide, Brand Fit: 5/5',
    creationDate: '2024-07-01',
    contentSnId: 'BLG-INFB-LEAD-20240701-QRST',
    daypart: 'Morning',
    spotLength: 'N/A',
    parentCompany: 'Digital Solutions Co.',
    brand: 'LeadGenius',
    product: 'Marketing Automation Tool',
    brandSafety: { isSafe: true, flags: [], reasoning: '' },
    status: 'Approved',
    contentType: 'Endorsed',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 78,
    roas: 3.5,
    spend: 10000,
    cpa: 45,
  },
  {
    id: uuidv4(),
    creator: 'PodcastNet',
    name: 'Premium Headphones Ad',
    type: 'Audio',
    length: '60s',
    campaign: 'Brand Awareness',
    tags: 'Interview, Sponsorship',
    creationDate: '2024-07-18',
    contentSnId: 'AUD-PODN-BRND-20240718-UVWX',
    daypart: 'Commute',
    spotLength: '60s',
    parentCompany: 'AudioWave Media',
    brand: 'SoundScapes',
    product: 'Premium Headphones',
    brandSafety: { isSafe: true, flags: [], reasoning: '' },
    status: 'New',
    contentType: 'Branded',
    thumbnail: 'https://placehold.co/80x60.png',
    contentScore: 71,
    roas: 2.8,
    spend: 7500,
    cpa: 52,
  },
];

    